name: Deploy to EC2

# Trigger on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to EC2 via SSH
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Pull latest code on EC2
        run: |
          aws ssm send-command \
            --instance-ids "i-0ce24949367e96ab1" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["rm -rf /home/ubuntu/django-github-actions", "cd /home/ubuntu", "chmod +x /home/ubuntu/UserData.sh", "bash UserData.sh"]' \
            --output text

